#!/usr/bin/env bash
# Function that returns "Best School" 10x
#show Hi before Best School

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( count++ ))
done
