#!/usr/bin/env bash
# Function that returns "Best School" 10x
#show Hi before Best School

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 3 ]
	then
		echo "bad luck"
	elif [ $count -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( count++ ))
done
