#!/usr/bin/env bash
# Function that returns

hour=0

while [ $hour -le 12 ]
do
	echo "Hour : $count"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		(( minute++ ))
	done
	(( hour++ ))
done
